package com.consultoraestrategia.ss_crmeducativo.portal.main.entities;

public enum TipoMenu {
    COLEGIO_EVENTO,
    COLEGIO_CALENDARIO,
    COLEGIO_DIRECTORIO,
    ESTUDIANTE_TAREAS,
    ESTUDIANTE_ASISTENCIA,
    ESTUDIANTE_CONDUCTA,
    ESTUDIANTE_ESTADOCUENTA,
    ESTUDIANTE_CURSO,ESTUDIANTE_RUBROS;
}
